config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'lessons/index'

  get 'lessons/new'

  resources :lessons

  root "lessons#index"
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	has_many :vocabularies, dependent: :destroy
	has_many :sentences, dependent: :destroy
	has_many :books, dependent: :destroy
	accepts_nested_attributes_for :vocabularies, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :sentences, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :books, reject_if: :all_blank, allow_destroy: true
	validates :lesson_name, :lesson_number, :presence => true

	def self.search(search)
	  if search
	    self.where('lesson_name LIKE ?', "%#{search}%")
	  else
	    self.all
		end
	end
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
	belongs_to :lesson
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
	belongs_to :lesson
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :find_lesson, only: [:show, :edit, :update, :destroy]

  def index
    # @lessons = Lesson.order('lessons.lesson_name ASC').all
    @lessons = Lesson.search(params[:search]).paginate(page: params[:page], per_page: 10)
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'file_name',   # Excluding ".pdf" extension.
        template: 'lessons/show.pdf.slim',
        layout: 'pdf.html.erb',
        show_as_html: params[:debug].present?
      end
    end
  end

  def edit
  end

  def update
    if @lesson.update(lesson_params)
			redirect_to @lesson
		else
			render 'edit'
		end
  end

  def destroy
    @lesson.destroy
    redirect_to root_path
    # flash[:success] = "Lesson was successfully deleted."
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to @lesson
    else
      render 'new'
    end
  end
  private

  def lesson_params
    params.require(:lesson).permit(:lesson_name, :lesson_number,
    vocabularies_attributes: [:id, :word, :meaning, :_destroy],
    sentences_attributes: [:id, :sentence, :meaning, :_destroy],
    books_attributes: [:id, :page_start, :page_end, :book_name, :_destroy])
  end

  def find_lesson
    @lesson = Lesson.find(params[:id])
  end
end


def project_params
    params.require(:project).permit(:name, :description, tasks_attributes: [:id, :description, :done, :_destroy])
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teachingtool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- <div class="main-nav">
      <nav>
        <ul>
          <li><a href="/lessons/index">All Lessons</a></li>
          <li><a href="/lessons/new">New Lesson</a></li>
          <li><a href="#">Place Holder</a></li>
          <li><a href="#">Place Holder</a></li>
        </ul>
      </nav>
    </div> -->
  </section>
<%= yield %>

</body>
</html>

<!-- This needs to be added to this page for login alerts. -->

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<head>
  <title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag 'application' %>
  <link href="http://fonts.googleapis.com/earlyaccess/hanna.css" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/lessons/_book_fields.html.slim
nested-fields
  ul.book-create
    li= f.input :book_name
    li= f.input :page_start
    li= f.input :page_end
    li= link_to_remove_association "remove book", f
      

app/views/lessons/_form.html.slim
= simple_form_for @lesson do |f|
	.panel-body
		= f.input :lesson_name, input_html: { class: 'form-control' }
		= f.input :lesson_number, input_html: { class: 'form-control' }

	.panel
		.new-book
			h3 Book
			#book
				= f.simple_fields_for :books do |book|
					= render 'book_fields', f: book
				.links
					= link_to_add_association 'add book', f, :books
		.new-vocab
			h3 Vocabulary
			#vocabulary
				= f.simple_fields_for :vocabularies do |vocabulary|
					= render 'vocabulary_fields', f: vocabulary
				.links
					= link_to_add_association 'add Vocabulary', f, :vocabularies
		.new-sentences
			h3 Sentences
			#sentence
				= f.simple_fields_for :sentences do |sentence|
					= render 'sentence_fields', f: sentence
				.links
					= link_to_add_association 'add sentence', f, :sentences

			div class="controls"
				= f.button :submit, class: "btn btn-default"

app/views/lessons/_navbar.html.slim
ul class="main-nav"
  li
    a href="/lessons/index" All Lessons
  li
    a href="/lessons/new" New Lesson
  li
    a href="#" Place Holder
  li
    a href="#" Place Holder

app/views/lessons/_sentence_fields.html.slim
.nested-fields
  ul.sentence-create
    li= f.input :sentence
    li= f.input :meaning
    li= link_to_remove_association "remove sentence", f

app/views/lessons/_vocabulary_fields.html.slim
.nested-fields
  ul.vocabulary-create
    li= f.input :word
    li= f.input :meaning
    li= link_to_remove_association "remove vocabulary", f

app/views/lessons/edit.html.slim
 hr
	=render({partial: 'form', locals: {lesson: @lesson}})
	= link_to "Cancel", lesson_path

app/views/lessons/index.html.slim
header.all-head
	h1 All Lessons

	= render partial: 'navbar'
section.all-list
	header.list-head
		h2 Lesson List
	= form_tag lessons_path, :method => 'get' do
		p
			= text_field_tag :search
			= submit_tag "Search", :class => "search"

    table class="all-table"
  		thead
  			tr
  				th Lesson Name
  				th #
  				th Remove
  		tbody.list
  			- @lessons.each do |lesson|
  				tr
  					td = link_to lesson.lesson_name, lesson, :class => "lessons"
  					td = lesson.lesson_number
  					td = link_to lesson_path(lesson), method: :delete, data: { confirm: "Delete this lesson? "}, :class => "delete-btn" do
  							i.fa.fa-trash


  	.apple_pagination
  		= will_paginate @lessons

app/views/lessons/new.html.slim
header class="lesson-head"
  h1 New Lessons
  = render partial: 'navbar'

section class="form-card"
  div class="head"
    p Create New Lesson
  = render partial: 'form'

app/views/lessons/show.html.slim
header class="show-head"
	h1 Lesson Information

= render partial: 'navbar'

/ Assigned Homework Section
div class="controls"
	= link_to "edit", edit_lesson_path, class: "btn btn-default"
	= link_to "back", lessons_url, class: "btn btn-default"
	= link_to "download pdf", lesson_path(@lesson, :format => "pdf"), class: "btn btn-default"

.magic-class
	div.container
		div.left-table-combo
			table.left-table
				p.school ELITE YEONHEE
				tr.homework
					th=
					th Homework
					th=
				tr.lesson-name
					td Lesson:
					td= @lesson.lesson_name
					td= @lesson.lesson_number
			table.books-table
				- @lesson.books.each do |book|
					tr
						td = book.book_name
						td = book.page_start
						td ~
						td = book.page_end
			table.reading-sign
				tr
					td Reading Sign
				br
					td 읽기 숙제 싸인해주세요

		table class="top-table"
			thead
				tr
					th
					th Word
					th Meaning
					th My Definition
			tbody
				- @lesson.vocabularies.each_with_index do |vocabulary, i|
					tr
						td align="center" =i+1
						td.columns = vocabulary.word
						td.columns = vocabulary.meaning
						td.columns

	/ Rewriting Vocabulary Section
	br


	h2.big-box Write Vocabulary Three Times & Meaning One Time. (단어를 3번 쓴 후 뜻을 한번 쓰세요.)

	table align="center" class="rewrite-table"
		- @lesson.vocabularies.each_with_index do |vocabulary, i|
			tr
				td width="60px" = i+1
				td width="350px" align="left" style="color: #B9BFC3;" = vocabulary.word
				td width="350px"
				td width="350px"
				td width="350px"

	/ Rewriting Sentences Section
	br
	h2 Copy the following sentences TWO times.

	ul
	- @lesson.sentences.each do |sentences|
		li.sample= sentences.sentence

	table class="sentence-table"
		- @lesson.sentences.each do |sentences|
			tr
				td colspan="1" &nbsp;
			tr
				td colspan="1" &nbsp;

	/ Pagebreak when printing page
	h2 class="splitter"
	/ Writing Sentences Section
	br
	h2 Make 5 sentences using today's vocabulary. (Do not use "I" as a subject more than once.)
	table class="sentence-table"
		- 5.times do |i|
			tr
				td width="1400px" colspan="1" text-align="left" = i+1

	/ Corrected Sentences Section
	br
	h2 Rewrite your 5 sentences using your teacher's corrections.
	table class="sentence-table"
		- 5.times do |i|
			tr
				td width="1400px" colspan="1" text-align="left" = i+1

	/ Practice Quiz Section
	br
	h2 Write the words next to the definition

	ul.mini-quiz-wordbank
		- @lesson.vocabularies.each do |vocabulary|
			li.mini-quiz-word= vocabulary.word

	/ table class="mini-quiz-table"
	/ 	- @lesson.vocabularies.each do |vocabulary|
	/ 		tr
	/ 			td = vocabulary.word
	br
	table.quiz-exercise
		- @lesson.vocabularies.each_with_index do |vocabulary, i|
			tr
				td.blank=i+1
				td -
				td.mini-quiz= vocabulary.meaning

app/views/lessons/show.pdf.slim
= wicked_pdf_stylesheet_link_tag "_wicked_show.scss"
= wicked_pdf_stylesheet_link_tag "application"

.magic-class
	div.container
		div.left-table-combo
			table.left-table
				p.school ELITE YEONHEE
				tr.homework
					th=
					th Homework
					th=
				tr.lesson-name
					td Lesson:
					td= @lesson.lesson_name
					td= @lesson.lesson_number
			table.books-table
				- @lesson.books.each do |book|
					tr
						td = book.book_name
						td = book.page_start
						td ~
						td = book.page_end
			table.reading-sign
				tr
					td Reading Sign
				br
					td 읽기 숙제 싸인해주세요

		table class="top-table"
			thead
				tr
					th
					th Word
					th Meaning
					th My Definition
			tbody
				- @lesson.vocabularies.each_with_index do |vocabulary, i|
					tr
						td align="center" =i+1
						td.columns = vocabulary.word
						td.columns = vocabulary.meaning
						td.columns

	/ Rewriting Vocabulary Section
	br


	h2.big-box Write Vocabulary Three Times & Meaning One Time. (단어를 3번 쓴 후 뜻을 한번 쓰세요.)

	table align="center" class="rewrite-table"
		- @lesson.vocabularies.each_with_index do |vocabulary, i|
			tr
				td width="60px" = i+1
				td width="350px" align="left" style="color: #B9BFC3;" = vocabulary.word
				td width="350px"
				td width="350px"
				td width="350px"

	/ Rewriting Sentences Section
	br
	h2 Copy the following sentences TWO times.

	ul
	- @lesson.sentences.each do |sentences|
		li.sample= sentences.sentence

	table class="sentence-table"
		- @lesson.sentences.each do |sentences|
			tr
				td colspan="1" &nbsp;
			tr
				td colspan="1" &nbsp;

	/ Pagebreak when printing page
	h2 class="splitter"
	/ Writing Sentences Section
	br
	h2 Make 5 sentences using today's vocabulary. (Do not use "I" as a subject more than once.)
	table class="sentence-table"
		- 5.times do |i|
			tr
				td width="1400px" colspan="1" text-align="left" = i+1

	/ Corrected Sentences Section
	br
	h2 Rewrite your 5 sentences using your teacher's corrections.
	table class="sentence-table"
		- 5.times do |i|
			tr
				td width="1400px" colspan="1" text-align="left" = i+1

	/ Practice Quiz Section
	br
	h2 Write the words next to the definition

	ul.mini-quiz-wordbank
		- @lesson.vocabularies.each do |vocabulary|
			li.mini-quiz-word= vocabulary.word

	/ table class="mini-quiz-table"
	/ 	- @lesson.vocabularies.each do |vocabulary|
	/ 		tr
	/ 			td = vocabulary.word
	br
	table.quiz-exercise
		- @lesson.vocabularies.each_with_index do |vocabulary, i|
			tr
				td.blank=i+1
				td -
				td.mini-quiz= vocabulary.meaning